Iteatime/Acrabadabra

- README.md
- package-lock.json
- package.json
Here I tried to implement one task that run Angular's and lambda's development servers using one command. I achieved this task using the concurrently package and creating two npm command in the package.json file. It logs those two consoles inside one and separates each using a number that prefixes every line.
> First try to serve lambda and angular with one command

- src/functions/status.js
Use the new javascript async/await syntax instead of callbacks.
> refactor: using async/await 

- src/app/cras/edit-cra/edit-cra.component.ts
Validation is triggered on submit
> Cpont show validation after modal close

- angular.json
- src/app/cras/edit-cra/edit-cra.component.ts
- src/index.html
- src/robots.txt
- src/sitemap.xml
Favicon created, SEO meta tag and files added.
> feat favicon and seo meta / files

- package-lock.json
- package.json
- src/polyfills.ts
> IE support

- src/app/app.module.ts
- src/app/cras/edit-cra/edit-cra.component.html
- src/app/cras/edit-cra/edit-cra.component.ts
- src/app/shared/mailto.directive.spec.ts
- src/app/shared/mailto.directive.ts
Add       : mailto directive
Change : email link to use mailto
> Mailto directive

- README.md
- package.json
Serve lambda through npx with inspection
> Enhance lambda debugging

- src/app/modules/calendar/components/calendar-selector/calendar-selector.component.ts
Fix the console error log when redirected during the calendar init
> Fix console error on redirect

- src/app/modules/timesheet/components/invoice-pdf/invoice-pdf.component.scss
Set a css property for white color background on invoice appendix tables
> fix background color of table

- src/app/shared/models/invoice.model.ts
Hide banking details only when none provided
Show them otherwise
> Change the hide condition of banking details

- .circleci/config.yml
- README.md
- package-lock.json
- package.json
- scripts/ci-validate.js
- scripts/config/karma-phantom.conf.js
To verify that the application passes the unit test before deployment, I added a script to run the tests before deployment.
> Unit tests on deploy

- .circleci/config.yml
- scripts/ci-validate.js
Fix the CircleCi config so a failing tests cause the job to fail and the Github check at the end
> HotFix Make the Circle CI job fail on test error

- e2e/features/I_receive_a_notification.feature
- e2e/features/enter_a_flat_fee_expense.feature
- e2e/features/enter_a_mileage_expense.feature
- e2e/features/enter_a_misc_expense.feature
- e2e/features/enter_an_invoice.feature
- e2e/features/enter_my_activity_report.feature
- e2e/features/notification.feature
- e2e/features/review_an_activity_report.feature
Reword some gherkin feature description
> HotFix better gherkin

- src/app/app.module.ts
- src/app/modules/notification/components/notifications/notifications.component.spec.ts
- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.html
- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.ts
- src/app/modules/timesheet/services/timesheet.service.spec.ts
- src/app/modules/timesheet/services/url-shortening.service.spec.ts
- src/app/modules/timesheet/services/url-shortening.service.ts
- src/app/shared/models/review-mail.model.ts
- src/environments/environment.ts
Ref to [this ticket](https://trello.com/c/CebatPPw/29-service-url-shortener)
Calls an external API (rebrandly.com) to shorten CRA links.
>  feat(links): URL shortening service for CRA generated links

- e2e/features/load_a_timesheet.feature
- package-lock.json
- package.json
- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.html
- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.scss
- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.ts
- src/app/modules/timesheet/services/timesheet.service.spec.ts
- src/app/modules/timesheet/services/timesheet.service.ts
- src/app/shared/services/localSave/local-save.service.spec.ts
- src/app/shared/services/localSave/local-save.service.ts
- src/app/shared/services/serialization/serialization.service.spec.ts
- src/app/shared/services/serialization/serialization.service.ts
ref to [this ticket](https://trello.com/c/9QDgcyhC/17-sauvegarder-les-donn%C3%A9es-de-mon-cra-localement)
> Add Timesheet saving to the local storage

- src/app/components/header/header.component.html
- src/app/components/header/header.component.scss
- src/app/components/header/header.component.ts
- src/app/components/home/home.component.html
- src/app/components/home/home.component.ts
- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.html
- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.scss
- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.ts
- src/app/modules/timesheet/components/timesheet-review/timesheet-review.component.html
- src/app/modules/timesheet/components/timesheet-review/timesheet-review.component.scss
- src/app/modules/timesheet/timesheet.module.ts
- src/app/modules/timesheet/timesheet.routes.ts
Create a layout component
Update timesheet routes
Ref to [this ticket](https://trello.com/c/gsb5GXZ6/47-cr%C3%A9ation-dun-composent-header)
> Refactor timesheet components

- angular.json
- package-lock.json
- package.json
- scripts/set-env.js
- src/app/components/header/header.component.html
- src/app/components/header/header.component.scss
- src/app/components/header/header.component.ts
- src/app/components/home/home.component.html
- src/app/components/home/home.component.scss
- src/app/components/home/home.component.ts
- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.ts
- src/app/modules/timesheet/timesheet.routes.ts
- src/app/shared/services/authentication/authentication.service.spec.ts
- src/app/shared/services/authentication/authentication.service.ts
- src/app/style/_vars.scss
Add Authentication
Update Identity branch
Add a service to manage Auth
Change popin link
Ref to [this ticket](https://trello.com/c/16lrvWNF/7-histoire-cr%C3%A9er-un-compte-prestataire)
> Provider authentication identity

- e2e/features/invoice_my_timesheet.feature
- src/app/modules/timesheet/components/timesheet-review/timesheet-review.component.html
- src/app/modules/timesheet/components/timesheet-review/timesheet-review.component.scss
- src/app/modules/timesheet/components/timesheet-review/timesheet-review.component.ts
- src/app/modules/timesheet/services/timesheet.service.spec.ts
- src/app/modules/timesheet/services/timesheet.service.ts
- src/app/shared/models/index.ts
Ref to [this ticket](https://trello.com/c/p5GrTeAB/8-histoire-facturer-un-cra-au-client-final)
> Transfer of informations for re-invoicing

- src/app/modules/timesheet/components/timesheet-edit/timesheet-edit.component.ts
> feat(app): unvalid shared timesheet

- e2e/features/enter_an_invoice.feature
- src/app/modules/timesheet/components/invoice-form/invoice-form.component.html
- src/app/modules/timesheet/components/invoice-form/invoice-form.component.scss
> Mkanel add optional tag fields

- e2e/features/invoice_my_timesheet.feature
- src/app/modules/timesheet/services/timesheet.service.spec.ts
- src/app/modules/timesheet/services/timesheet.service.ts
> add client infos with timesheet transfer
